Update entryTrackerCICD.yml

diff --git a/.github/workflows/entryTrackerCICD.yml b/.github/workflows/entryTrackerCICD.yml
--- a/.github/workflows/entryTrackerCICD.yml
+++ b/.github/workflows/entryTrackerCICD.yml
@@ -105,7 +105,7 @@ jobs:
       - name: Wait for 1 minutes
         run: sleep 60
 
-      # Get the set up SSH key
+      # Get and set up SSH key
       - name: Get SSH key
         run: |
           echo "${{ secrets.SSH_KEY }}" > ssh_key.pem
@@ -116,8 +116,8 @@ jobs:
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PUBLIC_IP }} "tail -n 15 /tmp/userdata.log"
 
-      # Run e2e-tests.sh on the instance using SSH
-      - name: Run E2E Tests on EC2 via SSH
+      # Run e2e-tests.sh on the instance
+      - name: Run E2E Tests on EC2
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PUBLIC_IP }} "bash /home/ubuntu/workspace/entryTracker_CICD/scripts/e2e-tests.sh"
 
@@ -130,7 +130,7 @@ jobs:
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PUBLIC_IP }} "tail -n 15 /tmp/e2e_tests.log"
 
-      # Check e2e-tests.sh log for success message
+      # Check e2e-tests.sh log
       - name: Check E2E Test Results
         run: |
           LOG_CONTENT=$(ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PUBLIC_IP }} "cat /tmp/e2e_tests.log")
@@ -147,7 +147,7 @@ jobs:
         run: aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com
 
       # Build, tag, and push the Docker image to Amazon ECR
-      - name: Build, tag, and push Docker image
+      - name: (CD) Build, tag, and push Docker image
         env:
           ECR_REGISTRY: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com
           ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
@@ -162,21 +162,38 @@ jobs:
         run: echo "PROD_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=PROD_INSTANCE" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)" >> $GITHUB_ENV
 
       # SSH into the PROD_INSTANCE and run docker-compose down
-      - name: Run docker-compose down
+      - name: (CD) Run docker-compose down
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} "docker-compose -f /home/ubuntu/workspace/entryTracker_CICD/docker-compose.yml down"
 
       # SSH into the PROD_INSTANCE and remove old Docker images
-      - name: Remove old Docker images
+      - name: (CD) Remove old Docker images from PROD
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} "docker image prune -af"
 
       # SSH into the PROD_INSTANCE and pull the latest Docker image
-      - name: Pull latest Docker image
+      - name: (CD) Pull latest Docker image to PROD
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} "docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest"
 
       # SSH into the PROD_INSTANCE and run docker-compose up
-      - name: Run docker-compose up
+      - name: (CD) Run docker-compose up
         run: |
           ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} "docker-compose -f /home/ubuntu/workspace/entryTracker_CICD/docker-compose.yml up -d"
+      
+      # Run Post-Deploy tests
+      - name: (CD) e2e-tests.sh on PROD_INSTANCE
+        run: |
+          ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} "bash /home/ubuntu/workspace/entryTracker_CICD/scripts/e2e-tests.sh"
+
+      # Check Post-Deploy tests
+      - name: (CD) Check Post-Deploy tests
+        run: |
+          LOG_CONTENT=$(ssh -i ssh_key.pem -o StrictHostKeyChecking=no ubuntu@${{ env.PROD_IP }} "cat /tmp/e2e_tests.log")
+          echo "$LOG_CONTENT"
+          if echo "$LOG_CONTENT" | grep -q "All health checks passed successfully."; then
+          echo "Post-Deploy tests passed. Service is up-to-date and running."
+            else
+          echo "Post-Deploy tests failed. Service is down!"
+          exit 1
+            fi
